apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-rest
  labels:
    app: spring-petclinic-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic-rest
  template:
    metadata:
      labels:
        app: spring-petclinic-rest
    spec:
      containers:
        - name: spring-petclinic-rest
          image: spring-petclinic-rest:ci
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9966
          readinessProbe:
            httpGet:
              path: /petclinic/actuator/health
              port: 9966
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /petclinic/actuator/health
              port: 9966
            initialDelaySeconds: 30
            periodSeconds: 20