apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-rest
  labels:
    app: spring-petclinic-rest
spec:
  selector:
    app: spring-petclinic-rest
  ports:
    - name: http
      port: 80
      targetPort: 9966
  type: ClusterIP